def f():
    raise Exception()

f()
